[package]
name = "test_integrity"
version = "0.1.0"
authors = [ "zo-el <joelulahanna@gmail.com>", "jetttech <lisa.jetton@holo.host>" ]
edition = "2021"

[lib]
name = "test_integrity"
crate-type = [ "cdylib", "rlib" ]

[dependencies]
serde = "1.0"
holochain_deterministic_integrity = "=0.0.10"
